//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamexProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamexDatabaseEntities : DbContext
    {
        public GamexDatabaseEntities()
            : base("name=GamexDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DlcDetail> DlcDetails { get; set; }
        public virtual DbSet<GameDetail> GameDetails { get; set; }
        public virtual DbSet<PurchasedDlcDetail> PurchasedDlcDetails { get; set; }
        public virtual DbSet<PurchasedGameDetail> PurchasedGameDetails { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
