//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamexProject.Models
{
    using System;
    using System.Collections.Generic;
 

    public partial class PurchasedGameDetail
    {
        public PurchasedGameDetail()
        {

        }
        public PurchasedGameDetail(string gameId,string username,int inLibraryGameStatus)
        {
            GameId = gameId;
            Username = username;
            InLibraryGameStatus = inLibraryGameStatus;
        }
        public int PGiD { get; set; }
        public string GameId { get; set; }
        public string Username { get; set; }
        public Nullable<int> InLibraryGameStatus { get; set; }
    
        public virtual GameDetail GameDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
