//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamexProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedDlcDetail
    {

        public PurchasedDlcDetail()
        {

        }
        public PurchasedDlcDetail(string dlcId,string username,int inLibraryDlcSatus)
        {
            DlcId = dlcId;
            Username = username;
            InLibraryDlcStatus = inLibraryDlcSatus;
        }
        public int PDiD { get; set; }
        public string DlcId { get; set; }
        public string Username { get; set; }
        public Nullable<int> InLibraryDlcStatus { get; set; }
    
        public virtual DlcDetail DlcDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
